### ISSUE TITLE
ActiveForm валидция перестает работать через ajax 

### ISSUE THREAD

**Issue by allcho** [manchenkoff/yii2-recaptcha3#1]
После того как добавляю в форму $form->field($model, 'captcha')->widget(ReCaptchaWidget::class, ['action' => 'login']);
ActiveForm перестает валидировать через ajax и перезагружает страницу
 в ActiveForm стоит 'enableAjaxValidation' => true,

**Comment by manchenkoff** [comment]
1. Сама по себе капча не очень совместима с многократной AJAX валидацией.
2. Нужно иметь в виду, что AJAX валидация на стороне контроллера должна возвращать JSON массив результатов валидации
3. Когда Yii выполняет отправку AJAX запроса на валидацию, на самом деле еще не происходит заполнение самого скрытого поля формы, т.к. оно подвязано на событие **onsubmit**.

Сделано это по причине того, что в официальной [документации Google](https://developers.google.com/recaptcha/docs/v3) есть пометка

```
Note: reCAPTCHA tokens expire after two minutes. If you're protecting an action with reCAPTCHA, make sure to call execute when the user takes the action rather than on page load.
```

Т.е. если сделать это поле валидируемым на AJAX-запросы, то не факт, что не истечет время ожидания до заполнения самой формы, а обновить его уже не получится.

Поэтому, в случае включенного поля **enableAjaxValidation** у Yii **ActiveForm** можно использовать следующий хак - добавить к правилу валидации **ReCaptchaValidator** условие выполнения **when**:

```
[
    'captcha',
    ReCaptchaValidator::class,
    'score' => 0.8,
    'action' => 'login',
    'when' => function () {
        return !Yii::$app->request->isAjax;
    },
],
```

Это будет вызывать валидатор только при отправке **не AJAX-запроса** на **submit** формы. Итого, получаем примерно следующее:

**Правила валидации формы**
```php
public function rules()
{
    return [
        [['firstname', 'lastname', 'email'], 'required'],
        [['firstname', 'lastname', 'email'], 'string', 'min' => 5],
        [
            'captcha',
            ReCaptchaValidator::class,
            'score' => 0.8,
            'action' => 'login',
            'when' => function () {
                return !Yii::$app->request->isAjax;
            },
        ],
    ];
}
```

**Код отображения формы**
```php
<?php $form = ActiveForm::begin(['enableAjaxValidation' => true]); ?>
  <?= $form->field($model, 'firstname')->textInput(['autofocus' => true]) ?>
  <?= $form->field($model, 'lastname')->textInput() ?>
  <?= $form->field($model, 'email')->textInput() ?>

  <?= $form->field($model, 'captcha')->widget(ReCaptchaWidget::class, ['action' => 'login']); ?>

  <div class="form-group">
      <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
  </div>
<?php ActiveForm::end(); ?>
```

**Экшн контроллера**
```php
if ($model->load(Yii::$app->request->post())) {
    // валидация формы через AJAX
    if (Yii::$app->request->isAjax) {
        Yii::$app->response->format = Response::FORMAT_JSON;
        return ActiveForm::validate($model);
    }

    // валидация формы при submit
    if ($model->validate()) {
        return $this->goHome();
    }
}
```

**Comment by allcho** [comment]
Все сделал, не помогло. В общем я в network посмотрел, что без этого виджета в форме 
  **<?= $form->field($model, 'captcha')->widget(ReCaptchaWidget::class, ['action' => 'login']); ?>**   при нажатии на кнопку submit отправляется XHR(AJAX) запрос, но как только я помещаю строку Вашего виджета в ActiveForm, то при нажатии на кнопку, инициатором запроса является **document** Тоесть нет AJAX запроса

Может Вы знаете почему, сам тоже сейчас копаю, если что у меня форма в модальном окне, и вот подробные настройки 

```
 <?php $form = ActiveForm::begin([
        'id' => 'form-signup',
        'enableAjaxValidation' => true,
        'validateOnBlur' => false,
        'validateOnChange' => false,
        'action' => ['auth/signup'],
        'options' => [
                'class' => 'auth-form__form'
        ]
     ]); ?>
```

**Comment by manchenkoff** [comment]
@allcho а можете проверить работу без модального окна? Сильно сузит поиск проблемы)

Есть предположение, что проблема именно в JS-обработчике заполнения скрытого поля, но нужно подтвердить баг без модального окна

**Comment by allcho** [comment]
Без модального окна тоже самое, да скрытое поле, которое выводит Ваш виджет - пустое `<input type="hidden" id="signupform-captcha" name="SignupForm[captcha]" value="">
`

**Comment by allcho** [comment]
Хотя js из Вашего расширения грузится в самом низу, после jquery 
`<script>grecaptcha.ready(function() {
    let form = document.querySelector('#signupform-captcha').closest('form');
    
    form.onsubmit = (e) => {
        e.preventDefault();
        
        grecaptcha
            .execute('reCAPTCHA.siteKey', {action: 'signup'})
            .then(function(token) {
                document.querySelector('#signupform-captcha').value = token;
                form.submit();
            });
    };
});</script>`

**Comment by manchenkoff** [comment]
@allcho спасибо, посмотрю, что с этим можно сделать

**Comment by allcho** [comment]
> @allcho спасибо, посмотрю, что с этим можно сделать

В общем тут  вместо document.querySelector, я поставил  document.getElementById
`grecaptcha.ready(function() {
    let form = document.getElementById('#{$id}').closest('form');
    console.log(form);
    form.onsubmit = (e) => {
        e.preventDefault();
        
        grecaptcha
            .execute('{$this->apiKey}', {action: '{$this->action}'})
            .then(function(token) {
                document.getElementById('#{$id}').value = token;
                form.submit();
            });
    };
});
JS;`

При нажатии на submit стал отправляться AJAX, но поле так и не заполняется 
 **["captcha"]=> array(1) { [0]=> string(36) "Google reCAPTCHA verification failed" }**

**Comment by allcho** [comment]
В общем картина такая, AJAX в моем случае не работал из за  form.submit(); Его убрал и заработало. И вот что заметил, что это поле ` <input type="hidden" id="signupform-captcha" name="SignupForm[captcha]" value=""> `  value заполняется только после нажатия кнопки SUBMIT, естественно  валидация не проходит ` "signupform-captcha":["Google reCAPTCHA verification failed"]}` Сейчас еще попробую, покопаюсь

**Comment by manchenkoff** [comment]
@allcho да, все так, submit не расчитан на заполнение поля без вызова, над фиксом думаю, чтобы можно было и так и так использовать, как сделаю PR - обязательно тегну, спасибо за предоставленную информацию

**Comment by manchenkoff** [comment]
Сделал фикс #2 

Заставить работать с включенными **validateOnBlur** или **validateOnChange** не удалось, т.к. нужно переделывать скрипт **yiiActiveForm.js**, без этого он сам в фоне отправляет все поля ActiveForm на валидацию и, как следствие, токен из капчи пройдет только первый раз.

В виджет добавил новый атрибут **preloading**, с ним капча запрашивается на загрузке формы и каждые 2 минуты перезагружается в скрытом поле, а также сбрасывается на **submit** самой формы, чтобы при повторной отправке через нажатие на кнопку был уже новый токен.

Итого, код формы в представлении, который должен сработать
```php
<?php $form = ActiveForm::begin(
    [
        'id' => 'example-form',
        'enableAjaxValidation' => true,
        'validateOnBlur' => false,
        'validateOnChange' => false,
    ]
); ?>

<?= $form
        ->field($model, 'captcha')
        ->widget(
                ReCaptchaWidget::class,
                ['action' => 'login', 'preloading' => true]
        ); ?>
```
