### ISSUE TITLE
Using with simple form

### ISSUE THREAD

**Issue by tonykor** [manchenkoff/yii2-recaptcha3#3]
Hello, is there an ability to use with simple form
Html::hiddenInput()
Html::ActiveHiddenInput()
? 

Thanks

**Comment by manchenkoff** [comment]
Hey @tonykor, according to the Yii documentation, **hiddenInput()** method will create **<input>** tag only with predefined attributes and you won't be able to use custom scripts and callbacks, that is why you have to use a custom widget.

**Source of a default hiddenInput() method**
```
public static function hiddenInput($name, $value = null, $options = [])
{
    return static::input('hidden', $name, $value, $options);
}
```

**Source of ReCaptcha widget method**
```
public function run(): string
{
    $this->enableScripts();
    $this->setUpActiveField();
    $this->enableReCaptchaCallbacks();

    return Html::activeHiddenInput($this->model, $this->attribute, ['value' => '']);
}
```

So actually, you use **Html::activeHiddenInput()** inside of ReCaptcha Widget.

P.S. 
If you have issues with the integration of this field into your form, you can share it here and we will figure it out 👍

**Comment by manchenkoff** [comment]
Closed due to inactivity
